language: node_js

node_js:
- node

notifications:
  email: false
  slack: programwarscardgame:u1VhNgRjj1X8gxpEWhfLw6MP#builds

addons:
  code_climate:
    repo_token: 814d39d2092e7f3b870f9a455dad28295a4aa15e611472ecca5a6ae547a536f6
  ssh_known_hosts:
    - cullen.io

before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

cache:
  directories:
  - node_modules
install:
- npm install karma-firefox-launcher
- npm install jasmine-core
- npm install karma-chrome-launcher
- npm install karma-jasmine

script:
- npm run test

after_success:
- npm install -g codeclimate-test-reporter --save-dev
- codeclimate-test-reporter < ./test/unit/coverage/lcov.info
#- openssl aes-256-cbc -K $encrypted_85d54e705e41_key -iv $encrypted_85d54e705e41_iv -in deploy_key2.enc -out deploy_key2.pem -d
- eval "$(ssh-agent -s)" #start the ssh agent
#- chmod 600 deploy_key2.pem # this key should have push access
- ssh-add $ssh-private
- git remote add deploy  ssh://git@cullen.io/var/repo/programwars.git
- git push deploy


